name: Publish Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: anodin-app
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        buildargs: --tag anodin-app:$(date +%s)
